variables:
    RELEASE_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-g${CI_COMMIT_SHORT_SHA}-b${CI_PIPELINE_ID}"

include:
  - project: "devops/support"
    ref: master
    file:
      - "includes/build/rust/crates-io-mirror.yml"
      - "includes/reports/cargo-junit.yml"
      - "includes/docs/rustdoc.yml"

stages:
  - check
  - build
  - test
  - deploy

default:
    tags:
      - linux-docker
    image: ${PLG_CI_DOCKER_TAG}/rusty-python:latest

fmt:
    stage: check
    script:
      - cargo fmt -- --check

clippy:
    stage: check
    script:
      - cargo clippy --tests -- --deny warnings
      - cargo clippy --tests --no-default-features -- --deny warnings

compile:
    stage: build
    script:
      - cargo build
      - cargo build --no-default-features

package:
    stage: build
    script:
      - cargo package
    artifacts:
        name: "${RELEASE_NAME}-package"
        paths:
          - target/package

runtests:
    stage: test
    script:
      - cargo test
      - cargo test --no-default-features
